---
- name: Update and upgrade apt packages
  hosts: all 
  become: yes
  tasks:
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      apt:
        update_cache: yes

    - name: Update packages with yum
      when: ansible_pkg_mgr == 'yum'
      yum:
        name: '*'
        state: latest

    - name: Upgrade packages with apt
      when: ansible_pkg_mgr == 'apt'
      apt:
        upgrade: dist

    - name: Upgrade packages with yum
      when: ansible_pkg_mgr == 'yum'
      yum:
        name: '*'
        state: latest
        exclude: kernel*

    - name: check if system reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: send discord message
      uri:
        url: "https://discord.com/api/webhooks/1165248989256482866/QpwyRisZOjmtIfOnO__bjWaBPpW56lm2ogu9B0yU_eMwRQLq58YQlPiWkae4cfrp5e8u"
        method: POST
        body_format: json
        body: '{"content": "Reboot is required on {{ inventory_hostname }}"}'
        headers:
          Content-Type: application/json
        status_code: 204
      when: reboot_required.stat.exists