---
- name: Check Logical Volumes on a Server
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Gather volume group information
      command: vgs --noheadings --units m -o vg_name,vg_size,vg_free
      register: vg_info

    - name: Print volume group information
      debug:
        var: vg_info.stdout_lines

    - name: Gather logical volume information
      command: lvs --noheadings --units m -o lv_name,lv_size,vg_name
      register: lv_info

    - name: Print logical volume information
      debug:
        var: lv_info.stdout_lines

    - name: Ensure logical volumes are present
      assert:
        that:
          - lv_info.stdout_lines | length > 0
        fail_msg: "No logical volumes found on the server."
        success_msg: "Logical volumes found on the server."
